---
# tasks file for webhost
- name: installing "{{ pkg }}"
  yum:
    name: "{{ pkg }}"
    state: present
- name: copy page 
  copy: 
    src: hello.html
    dest: /var/www/html/index.html
  notify: 
  - restart_httpd
- name: starting "{{ pkg }}"
  service:
    name: "{{ pkg }}"
    state: started
    enabled: yes