---
- hosts: web # selecting group from inventory file 
  remote_user: test
  become: true # act like sudo for above user 
  vars_files: # calling external varilable file 
    - ../variables/myvar1.yml
  tasks: # here we will define modules to use 
  - yum: 
     name: git 
     state: present # present | installed | lastest -- we can use 
  - yum: 
     name: "{{ pkg  }}" 
     state: present 
  - user:
     name: "{{ my_user }}"
     password: "{{ 'Hello@123' | password_hash('sha512') }}" # --- > /etc/shadow
  - debug: 
      msg: "hey user {{ my_user }} got created !!"
  - copy:
      src: ../webapp/ashu.html
      dest: /var/www/html/index.html 
  - service:
      name: "{{ pkg }}"
      state: started
      enabled: yes


   